### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by sjllls** [cryptomilk/android_kernel_sony_msm8998#50]
Kernel will bootloop on branch "lineageos-15.1" if build automatically by using "make -j8 bacon".
But it could boot by compiling kernel manually.
Tested on maple. Build on 2019.05.08.

**Comment by cryptomilk** [comment]
Log or ramoops?

**Comment by sjllls** [comment]
@cryptomilk Only could see Sony Logo, there is no  log.
It could boot if by compiling kernel manually ( Image.gz-dtb and ramdisk.img )
But bootloop by using "make -j8 bacon".

**Comment by sjllls** [comment]
Besides, there is another issue, I built LineageOS 15.1 with @derfelot device tree.
By replacing derfelot's boot.img, I could finally enter the desktop.
But wifi, camera, baseband, flashlight all are broken.
Here is the log.
[maple_los15_1.log](https://github.com/cryptomilk/android_kernel_sony_msm8998/files/3156007/maple_los15_1.log)
![Screenshot_20190508-062506_Settings](https://user-images.githubusercontent.com/29087038/57357308-3688fa80-71a5-11e9-842a-8652d4bfce29.png)

**Comment by sjllls** [comment]
@derfelot  I can't scan 5Ghz wifi on your lineage-15.1-20190328-UNOFFICIAL-maple.zip.
My phone is G8142, but dual sim cards work.

**Comment by cryptomilk** [comment]
Did you use a ROM with a different signing key before? If yes, then you need to wipe data. If the ROM doesn't boot doesn't mean it is a kernel problem. Did you do an engineering build to get logcat? You can also patch init to have selinux permissive and write logcat to the cache partition.

**Comment by sjllls** [comment]
> Did you use a ROM with a different signing key before? If yes, then you need to wipe data. If the ROM doesn't boot doesn't mean it is a kernel problem. Did you do an engineering build to get logcat? You can also patch init to have selinux permissive and write logcat to the cache partition.

Hey, you may not understand my meaning.

If I use "make -j8" in android source directory, it will automatically  build system.img, boot.img, cache.img, etc.  
Kernel will be built automatically . After flashing this boot.img, phone will bootloop.
 
If I use "make -j8" in kernel source directory, it will build Image.gz-dtb.
By combining  Image.gz-dtb with ramdisk.img, I could also get a boot.img.
After flashing this boot.img, phone could boot successfully.

**Comment by derfelot** [comment]
> Besides, there is another issue, I built LineageOS 15.1 with @derfelot device tree.
> By replacing derfelot's boot.img, I could finally enter the desktop.
> But wifi, camera, baseband, flashlight all are broken.
> Here is the log.
> [maple_los15_1.log](https://github.com/cryptomilk/android_kernel_sony_msm8998/files/3156007/maple_los15_1.log)

I assume the issue with WiFi/radio/camera not working comes from the oem users/groups. did you use the verbatim los source or did you also revert anything in build and bionic? I don't have the two commits at hand right now that need to be reverted.

**Comment by derfelot** [comment]
also, please post you local_manifest. I made branches for dsds devices which you should use. note that we don't have a maple devices ourselves to test, and dsds devices are specific for the Asian market I believe. so debugging is a bit of a problem.

personally, I don't want to put any more effort into 15.1 myself. once things have stabilized for 16.0 on lilac, I will adopt for poplar and then can also try a maple build again.

**Comment by sjllls** [comment]
> > Besides, there is another issue, I built LineageOS 15.1 with @derfelot device tree.
> > By replacing derfelot's boot.img, I could finally enter the desktop.
> > But wifi, camera, baseband, flashlight all are broken.
> > Here is the log.
> > [maple_los15_1.log](https://github.com/cryptomilk/android_kernel_sony_msm8998/files/3156007/maple_los15_1.log)
> 
> I assume the issue with WiFi/radio/camera not working comes from the oem users/groups. did you use the verbatim los source or did you also revert anything in build and bionic? I don't have the two commits at hand right now that need to be reverted.

Yes, my Los sources repo from a mirror. 
But I don't modify your devices tree, I only build and verify your source code. Because I want to build a EAS kernel on your source code, I need to make sure your source code is right.

**Comment by derfelot** [comment]
I see. but this would explain why some services didn't work on your build.

are you planning on making a kernel for O or P? is it meant to be used for stock or los? the caf bases have changed. so if you want to make one for P you should use the 16.0 one.

**Comment by sjllls** [comment]
> > Besides, there is another issue, I built LineageOS 15.1 with @derfelot device tree.
> > By replacing derfelot's boot.img, I could finally enter the desktop.
> > But wifi, camera, baseband, flashlight all are broken.
> > Here is the log.
> > [maple_los15_1.log](https://github.com/cryptomilk/android_kernel_sony_msm8998/files/3156007/maple_los15_1.log)
> 
> I assume the issue with WiFi/radio/camera not working comes from the oem users/groups. did you use the verbatim los source or did you also revert anything in build and bionic? I don't have the two commits at hand right now that need to be reverted.

Yes, my Los sources repo from a mirror. 
But I don't modify your devices tree, I only build and verify your source code. Because I want to build a EAS kernel on your source code, I need to make sure your source code is right.

> also, please post you local_manifest. I made branches for dsds devices which you should use. note that we don't have a maple devices ourselves to test, and dsds devices are specific for the Asian market I believe. so debugging is a bit of a problem.
> 
> personally, I don't want to put any more effort into 15.1 myself. once things have stabilized for 16.0 on lilac, I will adopt for poplar and then can also try a maple build again.

Because of the network connection with github  is not stable, I don't write device tree in  local_manifest. I download them directly.

Kernel ---From cryptomilk, Branch: lineage-15.1
Vendor ----From derfelot, Branch : lineage-15.1
Maple ----From derfelot, Branch : lineage-15.1
Yoshino ---From cryptomilk, Branch: lineage-15.1
Common-treble ---From cryptomilk, Branch: lineage-15.1

The only issue I met on your Los15.1 ROM is 5Ghz wifi seems to be broken.

I will try to repo source again from LineageOS offcial source.

**Comment by sjllls** [comment]
> I see. but this would explain why some services didn't work on your build.
> 
> are you planning on making a kernel for O or P? is it meant to be used for stock or los? the caf bases have changed. so if you want to make one for P you should use the 16.0 one.

At first, I build a EAS kernel for stock P. It lags at Xperia Logo. I can't get  any log.
I also try to built Los16 for maple, but it bootloop.
So I plan to build the EAS kernel for Los15.1, it success, I will try Los16 again.

**Comment by derfelot** [comment]
> 
> 
> > also, please post you local_manifest. I made branches for dsds devices which you should use. note that we don't have a maple devices ourselves to test, and dsds devices are specific for the Asian market I believe. so debugging is a bit of a problem.
> > personally, I don't want to put any more effort into 15.1 myself. once things have stabilized for 16.0 on lilac, I will adopt for poplar and then can also try a maple build again.
> 
> Because of the network connection with github is not stable, I don't write device tree in local_manifest. I download them directly.
> 
> Kernel ---From cryptomilk, Branch: lineage-15.1
> Vendor ----From derfelot, Branch : lineage-15.1
> Maple ----From derfelot, Branch : lineage-15.1
> Yoshino ---From cryptomilk, Branch: lineage-15.1
> Common-treble ---From cryptomilk, Branch: lineage-15.1
> 
> The only issue I met on your Los15.1 ROM is 5Ghz wifi seems to be broken.
> 
> I will try to repo source again from LineageOS offcial source.
> 
> Here is the manifests.
> [manifests.zip](https://github.com/cryptomilk/android_kernel_sony_msm8998/files/3156340/manifests.zip)

Please use the lineage-15.1_init_dsds branch for yoshino instead. In maple there is already a device-specific init extension included to handle dsds variants, but it depends on this yoshino branch. See if you still get stuck at the Sony splash (which i suspect is an init issue rather than a kernel one).

As for building it again from source, please revert these two commits in build and bionic, otherwise some services will fail to start again:

https://github.com/LineageOS/android_bionic/commit/2de89a8d9d552f7bc4cd68f23c1a22b0715fd9c1
https://github.com/LineageOS/android_build/commit/784fbae86ac177f820777d47c2fe8b121c6960ab

**Comment by sjllls** [comment]
> Please use the lineage-15.1_init_dsds branch for yoshino instead. In maple there is already a device-specific init extension included to handle dsds variants, but it depends on this yoshino branch. See if you still get stuck at the Sony splash (which i suspect is an init issue rather than a kernel one).
> 
> As for building it again from source, please revert these two commits in build and bionic, otherwise some services will fail to start again:
> 
> [LineageOS/android_bionic@2de89a8](https://github.com/LineageOS/android_bionic/commit/2de89a8d9d552f7bc4cd68f23c1a22b0715fd9c1)
> [LineageOS/android_build@784fbae](https://github.com/LineageOS/android_build/commit/784fbae86ac177f820777d47c2fe8b121c6960ab)

OK, after I rebuild, I will feedback to you.
Thanks again.

**Comment by sjllls** [comment]
@derfelot  
I compiling the kernel sucessfully, but It bootloop.
Could you help me to check the errors?
https://github.com/sjllls/android_kernel_sony_msm8998/commits/lineage-15.1-EAS

**Comment by cryptomilk** [comment]
Help with which errors. You need to provide logcat or ramoops logs to see what is going on.

**Comment by sjllls** [comment]
> Help with which errors. You need to provide logcat or ramoops logs to see what is going on.

May I ask a question?
How could I get log if phone reboots after showing Sony Logo?

**Comment by derfelot** [comment]
check for ramoops in /sys/FS/pstore.

**Comment by cryptomilk** [comment]
Create an engineering build that adb is started early. Often you get a log before it reboots then. The sony logo is shown till the bootanimation service gets started.

**Comment by sjllls** [comment]
>  /sys/FS/pstore.

There is nothing in /sys/FS/pstore in twrp.

**Comment by sjllls** [comment]
> Create an engineering build that adb is started early. Often you get a log before it reboots then. The sony logo is shown till the bootanimation service gets started.

Adb logcat is always waiting for device.

**Comment by cryptomilk** [comment]
Set the device to permissive and log to /cache

For example like this:

https://github.com/cryptomilk/android_device_sony_yoshino/commit/829ba80a715224ec5917dbd27c0263b8c2a123dc

**Comment by cryptomilk** [comment]
Well you need to do that after /cache has been mounted

**Comment by sjllls** [comment]
> Set the device to permissive and log to /cache
> 
> For example like this:
> 
> [cryptomilk/android_device_sony_yoshino@829ba80](https://github.com/cryptomilk/android_device_sony_yoshino/commit/829ba80a715224ec5917dbd27c0263b8c2a123dc)

It seems this patch can't work on stock rom.
Finnally I dumped the ramoops.
[dmesg-ramoops-0.log](https://github.com/cryptomilk/android_kernel_sony_msm8998/files/3169101/dmesg-ramoops-0.log)
Source code:   Branch : 47.2.A.10.45
https://github.com/sjllls/Kernel_Yoshino_EAS

**Comment by derfelot** [comment]
Hard to get anything out of it. To me it looks like there is an issue during mounting. So this is stock? Did you disable selinux and dmverity to see if you get any further?

**Comment by sjllls** [comment]
> Hard to get anything out of it. To me it looks like there is an issue during mounting. So this is stock? Did you disable selinux and dmverity to see if you get any further?

Yes , this is stock.
It seems useless to disable selinux by  adding "androidboot.selinux=permissive" in cmd_line on stock.

**Comment by sjllls** [comment]
> use the lineage-15.1_init_dsds branch for yoshino instead

I used the lineage-15.1_init_dsds branch for yoshino instead and built again.
The new rom works fine with 5Ghz wifi, camera.
The only issue is only one of the two sim slots works. 
The second sim slot could be recognized. But the second sim card couldn't  be recognized.

**Comment by sjllls** [comment]
Core functions of EAS run successfully on Yoshino devices.
Here is the source codes.
https://github.com/sjllls/android_kernel_sony_msm8998/tree/lineage-15.1-EAS
We need powerHAL from Pixel2/XL to get full EAS support.
This patch should work on lineageOS16.0 too.
[sjllls/android_kernel_sony_msm8998@ 99e1d59](https://github.com/sjllls/android_kernel_sony_msm8998/commit/99e1d591ed75df03ed3333dc9b955fbf57c4568f)
@cryptomilk  @derfelot

**Comment by derfelot** [comment]
How does it perform? any improvements over our current scheduling?

**Comment by sjllls** [comment]
> How does it perform? any improvements over our current scheduling?

This kernel is still need  to optimize. So now I can't judge it's full performance.
I am build a new version with Pixel2's powerHAL. Then I can test it.

**Comment by cryptomilk** [comment]
Also I guess that init changes are needed to set it up

**Comment by sjllls** [comment]
> I guess that init changes are needed to set it up too.

You might refer my patch. I don't know how to write selinux rules, so I set it permissive.
sjllls/android_device_sony_yoshino-1 [@02e5c](https://github.com/sjllls/android_device_sony_yoshino-1/commit/02e5c5989d5f0716508a512a6b083708a1f86aab)
sjllls/android_device_sony_common-treble [@e5446](https://github.com/sjllls/android_device_sony_common-treble/commit/e54460f3246ebd7c0ab1808cb22ab4383d93c9e0)

**Comment by cryptomilk** [comment]
Running permissive is a malware invitation! I hope you do only run open source apps or apps from trusted sources.

**Comment by sjllls** [comment]
> Running permissive is a malware invitation! I hope you do only run open source apps or apps from trusted sources.

Yes, I understand it. Running permissive is not safe.
I successfully build the new EAS version of lineage15.1.
New PowerHAL from Pixel 2 XL works. System runs smoothly.
Geekbench Single-Core Source is 1866. Multi-Core Source is 5011.
This kernel is still need to optimize. 
I think EAS is more advanced than HMP.

**Comment by j4nn** [comment]
@sjllls, it seems I get the same issue booting a fresh build of LOS 15.1 as you originally reported here.
Have you managed to solve it somehow?

I tried to get a logcat with using the "HACK selinux permissive" and "HACK logcat to /cache/logcat.txt" commits from @cryptomilk, but there was nothing logged (file /cache/logcat.txt not present when booted into twrp). I cannot extract anything from /sys/fs/pstore/ - that directory is empty in twrp booted after the los15.1 boot hanging in initial sony boot logo.
The hanging is actually never ending, it is not a bootloop, I have to force reboot it via vol+ with power button hold for several seconds.

And I can confirm that if I rebuild the kernel manually, using the source tree as checked out in los15.1 repo with lineage-msm8998-yoshino-lilac_defconfig and combining the arch/arm64/boot/Image.gz-dtb with los15.1 built ramdisk, I can boot the built los15.1 ok.

I am using @cryptomilk's repositories in local manifest having revision="lineage-15.1" with all of them.
I have reverted the 2de89a8d9d552f7bc4cd68f23c1a22b0715fd9c1 commit in bionic and the 784fbae86ac177f820777d47c2fe8b121c6960ab commit in build/make.

I am using OUT_DIR_COMMON_BASE env var to move output directory out of tree should that make any difference. Tested only lineage_lilac-userdebug so far.
During the build I've got a Java errors related to javadoc or something, when tried to build the same way as los16 which worked (i.e. having all JDK_HOME, JAVA_HOME and JAVAC env variables unset).
But for los15.1 I had to set ANDROID_JAVA_HOME to my linux distro's jdk8 (icedtea-bin-3.10.0) in order to be able to finish the build.

I am trying to build proof los15.1 to have a buildable base for an experiment with locked xz1c, hoping to startup customized los15.1 from a temproot shell of stock fw as discussed kernel requirements with @derfelot.

Any idea how to solve the kernel boot hanging?
Thank you.

**Comment by j4nn** [comment]
Additional information: it seems that the kernel built within los15.1 tree (and build process) is significantly smaller ('kernel' file is 16,980,080 bytes) than the kernel built manually from the same sources and defconfig ('Image.gz-dtb' file is 17,716,537 bytes).
Extracted dtb from both kernel builds are identical. Extracted inkernel config.gz is also identical in both builds.
Boot image metadata differ accordingly (the kernel part size):
`Boot image detected`
` Part      	Size      	Pages	  Addr`
`-Kernel:   	16980080	4146 	0x8000`
`+Kernel:   	17716537	4326 	0x8000`
` Ramdisk:  	1451441 	355  	0x1000000`
` Secondary:	0       	0    	0xf00000`
` Tags:       0x100`
` Flash Page Size: 4096 bytes`
` DT Size: 0 bytes`
` OS Version: 8.1.0 patch level 2019-05-??`
`-ID: 68ab7d5447f0461df5625caf5b1e70fb0c2f6a7000`
`+ID: 19b52fd5969767438238f88bc5172d7e100dd296000`

**Comment by j4nn** [comment]
Could it be possible that LOS15.1 makefiles would gzip the dtb part of the kernel image?
Stock kernel seems to attach uncompressed cat of all dtb blobs to the Image.gz file.
Just an idea, too late tonight for further analysis.

**Comment by derfelot** [comment]
Did you change the start of the hack from on charger to somewhere early during init (like on post-fs?).

Am I understanding it right that if you build a clean lineage-15.1 the kernel will not boot, only if you build it manually afterwards? That is really odd, since not much has really changed since the last time I made a 15.1 build. You could try as a test to revert back to the state from before the .179 and .180 merges by @sjllls and see if that does anything- those I haven't tested myself and I don't have the time currently to test a 15.1 build anymore.

As for the dtb part, I don't remember anymore, would have to look that up.

**Comment by j4nn** [comment]
@derfelot, no I did not try to change the start - just cherry picked those two "hack" commits.
Yes, that's correct, a clean build od los 15.1 would not boot most likely because the kernel hangs too early, possibly before any partition is mounted (my guess). And if it is build manually after, from the same sources, same config, combined with los built ramdisk, it boots ok.

In my opinion it is not the changes in kernel source tree - it could be some changes in los 15.1 makefiles, that are out of kernel tree itself. That is something that could change just by repo syncing with newer date.
I will try to check that dtb build/integration hopefully in the evening, no time right now...

**Comment by j4nn** [comment]
a total blind shot: do we need to remove Android.bp file somewhere similarly as it is need with twrp-9.0 build?

**Comment by derfelot** [comment]
no, that shouldn't be necessary (actually I thought the 15.1 kernel doesn't have it)

On June 2, 2019 4:41:07 PM GMT+02:00, j4nn <notifications@github.com> wrote:
>a total blind shot: do we need to remove Android.bp file somewhere
>similarly as it is need with twrp-9.0 build?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cryptomilk/android_kernel_sony_msm8998/issues/50#issuecomment-498037104

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjllls** [comment]
> @derfelot, no I did not try to change the start - just cherry picked those two "hack" commits.
> Yes, that's correct, a clean build od los 15.1 would not boot most likely because the kernel hangs too early, possibly before any partition is mounted (my guess). And if it is build manually after, from the same sources, same config, combined with los built ramdisk, it boots ok.
> 
> In my opinion it is not the changes in kernel source tree - it could be some changes in los 15.1 makefiles, that are out of kernel tree itself. That is something that could change just by repo syncing with newer date.
> I will try to check that dtb build/integration hopefully in the evening, no time right now...

I think there should be some wrong parameters in MakeFiles.
Oreo seems use Clang to compile kernel. It failed.
We use GCC to compile it manually and it boot successfully.
It needs time to find the reason.
BTW, all are fine in Los16.

**Comment by j4nn** [comment]
@sjllls, oh, I have not realized that los 15.1 used clang instead of gcc - checked only builtin gcc string and assumed toolchain had been the same: both kernels uncompressed binaries contain the "(gcc version 4.9.x 20150123 (prerelease) (GCC) )" string.

There is an option used only with in-tree kernel build: -DCONFIG_AS_LSE=1
I tried to disable that with empty setting of
`lseinstr :=`
in arch/arm64/Makefile, the option disappeared, but it did not help with the hanging of in-tree built kernel (and it is still smaller than the external one).
Concerning dtb, it seems to be ok (attached uncompressed at least what I can see in the makefiles).

Could it be possible that if the kernel was built by clang, that it would still contain the above gcc string?

**Comment by sjllls** [comment]
@j4nn. I am not sure whether the kernel is compiled by Clang completely.
I also found the difference of the two kernels.
The dtb built by Los15.1 is larger than the one build by GCC.
So there should be something uncompressed or something added.
I am also finding the reason.
Besides, if you use other compiler, such as the one from Linaro, you will also bootloop.

**Comment by j4nn** [comment]
@sjllls, this is interesting - I tried to replace prebuilt gcc of los 15.1 with the one from los 16.0, but the kernel still hangs, so I checked the los 16.0 kernel to find this:
- los 16.0 builds the kernel via clang, the kernel image contains following instead of gcc string
`clang version 6.0.2`
- los 15.1 with gcc updated from los 16.0 builds the kernel via that gcc (still hangs), it contains following string
`gcc version 4.9.x 20150123 (prerelease) (GCC)`

It seems to me the size difference is not in dtb blobs being different but rather the uncompressed kernel binary, the `arch/arm64/boot/Image` already differs in size:
- built externally the size without dtb is 46668648
- built in los 15.1 tree (with updated prebuilt gcc from los16.0) it is 48766056

That is about 2MB bigger intree than external.

The `lseinstr :=` setting is set in arch/arm64/Makefile based on a check of linker feature. It seems the result is different in case of external build with external toolchain, but when I tried to override that setting to use the same result, it did not help with the hanging (but I could see the influence of the change as -DCONFIG_AS_LSE=1 option disappeared in in-tree los15.1 kernel build).

**Comment by derfelot** [comment]
Just to chime in, the reason why los16.0 builds the kernel with clang, is because we are telling it to now :) https://github.com/cryptomilk/android_device_sony_yoshino/commit/19b153222b908f5344b01911dd642b514d4b9368#diff-2e9712b5ed713bf372a83cc477f59a2a

**Comment by j4nn** [comment]
@derfelot, it is quite strange, because prebuilt gcc did not changed within los 15.1 git history (that can be viewed in my tree - the last commit there is from March 2018).
So it might be that recent kernel merges introduced some incompatibility that triggers hanging if compiled by los15.1 prebuilt gcc. But it is very strange that it did not help to use the prebuilt gcc from los 16.0 (tagged as android-9.0.0_r37).
Could it be that lineage-16.0 kernel branch contains any compatibility fix that is not present in lineage-15.1 branch of the kernel?
This is probably a hard one to answer.

I tried to build the kernel without the merge from sjllls, i.e. I've checked out 9457feceaa22a1cce86a02c50e9cfe99401435a9 revision (Merge pull request #46 from derfelot/lineage-15.1_updates) but it did not help with the hanging either.
Can you remember the build date of los 15.1 which you have tested last with your phone?
To try to revert kernel merges since that date?

**Comment by derfelot** [comment]
I have definitely tested all the PR's I made on my phone as well, so basically everything until the merges of .179 and .180.

Can you extract the defconfig from the two builds (in-line and manually built) using extract-ikconfig and compare the two?

**Comment by j4nn** [comment]
This is just insane.
I've found probably one of my very first builds of los 15.1 on the sdcard in my phone.
I know it did not work. Just tried it again to remember and it is the same - kernel hangs forever with black SONY logo. If the kernel from modpunk's `lineage-15.1-20181022-UNOFFICIAL-BETA8-lilac.zip` is flashed instead of the one built by me, it boots that my build just fine
- it was `lineage-15.1-20181026-UNOFFICIAL-lilac.zip`.

So I am afraid this problem must be caused by something in the build environment.

Concerning in kernel configs in the two builds (in-line and manually built) - they are identical.
Already checked that in https://github.com/cryptomilk/android_kernel_sony_msm8998/issues/50#issuecomment-497984490 comment.

**Comment by derfelot** [comment]
Ah right, missed that, sorry. This is totally weird, I'll have to think about this (and maybe check some recent lineage commits).

**Comment by j4nn** [comment]
In fact I had never get my build of los 15.1 working. But as that have been my first trials, I did not report it, assuming that there must be something wrong at my side.

And I guess there still is something different probably in our linux distros that make our los 15.1 kernel builds different.

Anyway, I am glad that los 16.0 build works, I guess that's the most important thing now.

It probably is not worth it to spend any more time with this issue, it clearly is depending on linux environment in which the build is done. And in fact, the reason I try los 15.1 is the experiment with locked phone, where I cannot replace the kernel anyway, so it probably does not matter, while I can boot it on unlocked test phone with externally built kernel.
Thank you.

**Comment by sjllls** [comment]
I already met this problem before I pushed the kernel update of 179,180.
In fact, I also tested the source code on April (the same date as derfelot build a permissive kernel for Maple), I also met this problem.
@j4nn @derfelot
